### ISSUE TITLE
Give overview of total hits rendered by certain search

### ISSUE THREAD

**Issue by Ileemans** [Odeuropa/explorer#104] opened 2023-11-22 13:58 UTC
A very helpful addition to the explorer would be if we display the amount of hits on the browse page. We do this on the smell source page, but it would be great to have this on the Browse page as well. That way you can see how much you are narrowing down the hits your search by selecting different options.

**Comment by rtroncy** [comment] 2023-11-22 14:06
We already largely discussed this. We have to disable counting on the Browse pages because it is too expensive computationally. I'm closing this issue as this is also a duplicate of #100

**Closed by rtroncy** 2023-11-22 14:06 UTC
Labels: question
